name: fit
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  animated_toggle_switch: ^0.8.3
  fl_chart: ^0.70.1
  firebase_core: ^3.10.0  # Updated to the latest version
  firebase_auth: ^5.4.0   # Updated to the latest version
  cloud_firestore: ^5.6.1 # Updated to the latest version
  image_picker: ^1.0.7    # Added for image selection
  battery_plus: ^4.0.2    # Added for battery status
  sensors_plus: ^3.0.5    # Added for accelerometer data
  torch_light: ^1.0.1
  geolocator: ^13.0.2
  pedometer: ^4.0.0
  connectivity_plus: ^5.0.2
  http: ^0.13.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dependency_overrides:
  collection: ^1.19.1  # Updated to the latest version (ensure compatibility)
  material_color_utilities: ^0.12.0  # Updated to the latest version
  meta: ^1.16.0  # Updated to the latest version

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0  # Updated to the latest version
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/Profile.png
    - assets/images/Message.png
    - assets/images/Lock.png
    - assets/images/HidePass.png
    - assets/images/google.png
    - assets/images/FB.png
    - assets/images/GetStarted.png
    - assets/images/DOB.png
    - assets/images/weight.png
    - assets/images/height.png
    - assets/images/Gender.png
    - assets/images/Home.png
    - assets/images/Activity.png
    - assets/images/Notification.png
    - assets/images/more.png
    - assets/images/DP.png
    - assets/images/P1.png
    - assets/images/P2.png
    - assets/images/P3.png
    - assets/images/P4.png
    - assets/images/Arrow.png
    - assets/images/P6.png
    - assets/images/P7.png
    - assets/images/P8.png
    - assets/images/P5.png
    - assets/images/A1.png
    - assets/images/N0.png
    - assets/images/N1.png
    - assets/images/N2.png
    - assets/images/N3.png
    - assets/images/N4.png
    - assets/images/N5.png
    - assets/images/N6.png
    - assets/images/boots.png
    - assets/images/DP2.png
    - assets/images/glass.png
    - assets/images/W1.png
    - assets/images/Graph.png
    - assets/images/Banner.png
    - assets/images/bed.png
    - assets/images/clock.png
    - assets/images/IconBed.png
    - assets/images/IconTime.png
    - assets/images/IconRepeat.png
    - assets/data/workout_details.json
    - assets/images/fullbody.jpeg
    - assets/images/lowerbody.jpg
    - assets/images/ABs.png
    - assets/images/upperbody.png
    - assets/images/stretch.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700
